// Regenerates src/data/galleryItems.js from the 5 renamed photo folders.
// Run: node scripts/generate-gallery.mjs
// Titles describe generic design concepts — never claimed client projects.
import { readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ASSETS_DIR = 'src/assets/vasupriy-interior-images-renamed'

const FOLDERS = [
  {
    folder: 'cafe-interiors',
    label: 'Cafe Interiors',
    description:
      'Cafe and hospitality interiors from our curated collection.',
  },
  {
    folder: 'commercial-interior-renders',
    label: 'Commercial Interiors',
    description:
      'Commercial interiors exploring light, material and volume.',
  },
  {
    folder: 'commercial-site-photos',
    label: 'Commercial Site',
    description:
      'On-site commercial spaces captured during real project stages.',
  },
  {
    folder: 'residential-interior-renders',
    label: 'Residential Interior',
    description:
      'Residential interiors balancing comfort and character.',
  },
  {
    folder: 'residential-site-photos',
    label: 'Residential Site',
    description:
      'Real residential spaces photographed on site and in detail.',
  },
]

const titleCase = (slug) =>
  slug
    .replace(/-\d+$/, '')
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')

const items = []
for (const { folder, label, description } of FOLDERS) {
  const files = readdirSync(join(ASSETS_DIR, folder))
    .filter((file) => file.endsWith('.jpg'))
    .sort()
  for (const file of files) {
    const base = file.replace(/\.jpg$/, '')
    items.push({
      id: `${folder}-${base}`,
      title: titleCase(base),
      category: label,
      image: `../assets/vasupriy-interior-images-renamed/${folder}/${file}`,
      imageAlt: `${titleCase(base)} — ${label.toLowerCase()} interior photograph`,
      description,
    })
  }
}

const ids = items.map((item) => item.id)
if (new Set(ids).size !== ids.length) {
  throw new Error('Duplicate gallery ids detected')
}

const entry = (item) => `  {
    id: '${item.id}',
    title: '${item.title.replace(/'/g, "\\'")}',
    category: '${item.category}',
    image: new URL(
      '${item.image}',
      import.meta.url,
    ).href,
    imageAlt: '${item.imageAlt.replace(/'/g, "\\'")}',
    description: '${item.description}',
  },`

const output = `// Curated gallery content for the Vasupriy Interiovilla Gallery page.
// AUTO-GENERATED by scripts/generate-gallery.mjs — do not edit by hand.
// Titles describe generic design concepts — they are not claimed client projects.
// Images resolve through Vite so this data also works in the Node test runner.

export const galleryCategories = [
  'All Projects',
${FOLDERS.map((entry) => `  '${entry.label}',`).join('\n')}
]

export const galleryItems = [
${items.map(entry).join('\n')}
]

export function filterGalleryItems(items, category = 'All Projects') {
  if (!category || category === 'All Projects') return items
  return items.filter((item) => item.category === category)
}

export function getGalleryItem(id) {
  return galleryItems.find((item) => item.id === id)
}

/* Compact page window: first two, last two and neighbours of the
   current page, with an ellipsis wherever pages are skipped. */
export function getPageWindow(current, total) {
  if (total <= 7) {
    return Array.from({ length: total }, (_, index) => index + 1)
  }
  const keep = new Set([1, 2, total - 1, total, current - 1, current, current + 1])
  const numbers = [...keep]
    .filter((number) => number >= 1 && number <= total)
    .sort((a, b) => a - b)
  const window = []
  let previous = 0
  for (const number of numbers) {
    if (number - previous > 1) window.push('…')
    window.push(number)
    previous = number
  }
  return window
}
`

writeFileSync('src/data/galleryItems.js', output)
console.log(`Wrote ${items.length} gallery items across ${FOLDERS.length} categories.`)
